language: node__js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
    
env:
  global:
  - NODE_ENV=test
  
install:
  - npm install

services:
  - postgresql
  
before_script:
  # - psql -c 'create database cyclops_backend;' -U postgres
  # - psql -c "CREATE USER cyclops WITH PASSWORD 'blue';" -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  # - npm install -g sequelize-cli

script:
  - npm run test

after_success:
  - npm run coverage
